apiVersion: v2
name: stopwatch-app
description: DevOps Challenge — Stopwatch & Clock Go application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Joao
keywords:
  - go
  - stopwatch
  - clock
  - kubernetes
